In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbs
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df=pd.read_csv('heart.csv')

In [3]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [4]:
for col in df.columns[:-1]:
    print(col , [df[col].unique()])

age [array([63, 37, 41, 56, 57, 44, 52, 54, 48, 49, 64, 58, 50, 66, 43, 69, 59,
       42, 61, 40, 71, 51, 65, 53, 46, 45, 39, 47, 62, 34, 35, 29, 55, 60,
       67, 68, 74, 76, 70, 38, 77], dtype=int64)]
sex [array([1, 0], dtype=int64)]
cp [array([3, 2, 1, 0], dtype=int64)]
trestbps [array([145, 130, 120, 140, 172, 150, 110, 135, 160, 105, 125, 142, 155,
       104, 138, 128, 108, 134, 122, 115, 118, 100, 124,  94, 112, 102,
       152, 101, 132, 148, 178, 129, 180, 136, 126, 106, 156, 170, 146,
       117, 200, 165, 174, 192, 144, 123, 154, 114, 164], dtype=int64)]
chol [array([233, 250, 204, 236, 354, 192, 294, 263, 199, 168, 239, 275, 266,
       211, 283, 219, 340, 226, 247, 234, 243, 302, 212, 175, 417, 197,
       198, 177, 273, 213, 304, 232, 269, 360, 308, 245, 208, 264, 321,
       325, 235, 257, 216, 256, 231, 141, 252, 201, 222, 260, 182, 303,
       265, 309, 186, 203, 183, 220, 209, 258, 227, 261, 221, 205, 240,
       318, 298, 564, 277, 214, 248, 255, 207, 223, 288, 160, 394, 315,
       246, 244, 270, 195, 196, 254, 126, 313, 262, 215, 193, 271, 268,
       267, 210, 295, 306, 178, 242, 180, 228, 149, 278, 253, 342, 157,
       286, 229, 284, 224, 206, 167, 230, 335, 276, 353, 225, 330, 290,
       172, 305, 188, 282, 185, 326, 274, 164, 307, 249, 341, 407, 217,
       174, 281, 289, 322, 299, 300, 293, 184, 409, 259, 200, 327, 237,
       218, 319, 166, 311, 169, 187, 176, 241, 131], dtype=int64)]
fbs [array([1, 0], dtype=int64)]
restecg [array([0, 1, 2], dtype=int64)]
thalach [array([150, 187, 172, 178, 163, 148, 153, 173, 162, 174, 160, 139, 171,
       144, 158, 114, 151, 161, 179, 137, 157, 123, 152, 168, 140, 188,
       125, 170, 165, 142, 180, 143, 182, 156, 115, 149, 146, 175, 186,
       185, 159, 130, 190, 132, 147, 154, 202, 166, 164, 184, 122, 169,
       138, 111, 145, 194, 131, 133, 155, 167, 192, 121,  96, 126, 105,
       181, 116, 108, 129, 120, 112, 128, 109, 113,  99, 177, 141, 136,
        97, 127, 103, 124,  88, 195, 106,  95, 117,  71, 118, 134,  90],
      dtype=int64)]
exang [array([0, 1], dtype=int64)]
oldpeak [array([2.3, 3.5, 1.4, 0.8, 0.6, 0.4, 1.3, 0. , 0.5, 1.6, 1.2, 0.2, 1.8,
       1. , 2.6, 1.5, 3. , 2.4, 0.1, 1.9, 4.2, 1.1, 2. , 0.7, 0.3, 0.9,
       3.6, 3.1, 3.2, 2.5, 2.2, 2.8, 3.4, 6.2, 4. , 5.6, 2.9, 2.1, 3.8,
       4.4])]
slope [array([0, 2, 1], dtype=int64)]
ca [array([0, 2, 1, 3, 4], dtype=int64)]
thal [array([1, 2, 3, 0], dtype=int64)]

In [5]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
df.corr()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
age,1.000000,-0.098447,-0.068653,0.279351,0.213678,0.121308,-0.116211,-0.398522,0.096801,0.210013,-0.168814,0.276326,0.068001,-0.225439
sex,-0.098447,1.000000,-0.049353,-0.056769,-0.197912,0.045032,-0.058196,-0.044020,0.141664,0.096093,-0.030711,0.118261,0.210041,-0.280937
cp,-0.068653,-0.049353,1.000000,0.047608,-0.076904,0.094444,0.044421,0.295762,-0.394280,-0.149230,0.119717,-0.181053,-0.161736,0.433798
trestbps,0.279351,-0.056769,0.047608,1.000000,0.123174,0.177531,-0.114103,-0.046698,0.067616,0.193216,-0.121475,0.101389,0.062210,-0.144931
chol,0.213678,-0.197912,-0.076904,0.123174,1.000000,0.013294,-0.151040,-0.009940,0.067023,0.053952,-0.004038,0.070511,0.098803,-0.085239
fbs,0.121308,0.045032,0.094444,0.177531,0.013294,1.000000,-0.084189,-0.008567,0.025665,0.005747,-0.059894,0.137979,-0.032019,-0.028046
restecg,-0.116211,-0.058196,0.044421,-0.114103,-0.151040,-0.084189,1.000000,0.044123,-0.070733,-0.058770,0.093045,-0.072042,-0.011981,0.137230
thalach,-0.398522,-0.044020,0.295762,-0.046698,-0.009940,-0.008567,0.044123,1.000000,-0.378812,-0.344187,0.386784,-0.213177,-0.096439,0.421741
exang,0.096801,0.141664,-0.394280,0.067616,0.067023,0.025665,-0.070733,-0.378812,1.000000,0.288223,-0.257748,0.115739,0.206754,-0.436757
oldpeak,0.210013,0.096093,-0.149230,0.193216,0.053952,0.005747,-0.058770,-0.344187,0.288223,1.000000,-0.577537,0.222682,0.210244,-0.430696
slope,-0.168814,-0.030711,0.119717,-0.121475,-0.004038,-0.059894,0.093045,0.386784,-0.257748,-0.577537,1.000000,-0.080155,-0.104764,0.345877
ca,0.276326,0.118261,-0.181053,0.101389,0.070511,0.137979,-0.072042,-0.213177,0.115739,0.222682,-0.080155,1.000000,0.151832,-0.391724
thal,0.068001,0.210041,-0.161736,0.062210,0.098803,-0.032019,-0.011981,-0.096439,0.206754,0.210244,-0.104764,0.151832,1.000000,-0.344029
target,-0.225439,-0.280937,0.433798,-0.144931,-0.085239,-0.028046,0.137230,0.421741,-0.436757,-0.430696,0.345877,-0.391724,-0.344029,1.000000

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [9]:
X=df.drop(columns=['target'])
Y=df['target']

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [11]:
[X.shape, X_train.shape, X_test.shape]

[(303, 13), (242, 13), (61, 13)]

In [12]:
[Y.shape, Y_train.shape, Y_test.shape]

[(303,), (242,), (61,)]

In [13]:
model = LogisticRegression()

In [14]:
model.fit(X_train, Y_train)

C:\Users\pavan\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [15]:
X_train_prediction=model.predict(X_train)
accu=accuracy_score(X_train_prediction, Y_train)
print(accu)
X_test_prediction=model.predict(X_test)
accu2=accuracy_score(X_test_prediction, Y_test)
print(accu2)

0.8512396694214877
0.819672131147541

# Building Predictive System

In [16]:
for i in range(200):
    tst=X_test.iloc[i].values
    type(tst)
    #tst=tst.reshape(1,-1)


    prd=model.predict([tst])
    print(X_test.iloc[i],'\n',prd)


    if(prd==[1]):
        print('The person has heart disease')
    else:
        print('The Person do not have heart disease')

age          45.0
sex           1.0
cp            0.0
trestbps    142.0
chol        309.0
fbs           0.0
restecg       0.0
thalach     147.0
exang         1.0
oldpeak       0.0
slope         1.0
ca            3.0
thal          3.0
Name: 255, dtype: float64
 [0]
The Person do not have heart disease
age          29.0
sex           1.0
cp            1.0
trestbps    130.0
chol        204.0
fbs           0.0
restecg       0.0
thalach     202.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 72, dtype: float64
 [1]
The person has heart disease
age          52.0
sex           1.0
cp            3.0
trestbps    152.0
chol        298.0
fbs           1.0
restecg       1.0
thalach     178.0
exang         0.0
oldpeak       1.2
slope         1.0
ca            0.0
thal          3.0
Name: 83, dtype: float64
 [1]
The person has heart disease
age          54.0
sex           1.0
cp            0.0
trestbps    122.0
chol        286.0
fbs           0.0
restecg       0.0
thalach     116.0
exang         1.0
oldpeak       3.2
slope         1.0
ca            2.0
thal          2.0
Name: 268, dtype: float64
 [0]
The Person do not have heart disease
age          52.0
sex           1.0
cp            2.0
trestbps    138.0
chol        223.0
fbs           0.0
restecg       1.0
thalach     169.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            4.0
thal          2.0
Name: 92, dtype: float64
 [1]
The person has heart disease
age          68.0
sex           0.0
cp            2.0
trestbps    120.0
chol        211.0
fbs           0.0
restecg       0.0
thalach     115.0
exang         0.0
oldpeak       1.5
slope         1.0
ca            0.0
thal          2.0
Name: 105, dtype: float64
 [1]
The person has heart disease
age          55.0
sex           1.0
cp            0.0
trestbps    132.0
chol        353.0
fbs           0.0
restecg       1.0
thalach     132.0
exang         1.0
oldpeak       1.2
slope         1.0
ca            1.0
thal          3.0
Name: 180, dtype: float64
 [0]
The Person do not have heart disease
age          60.0
sex           1.0
cp            0.0
trestbps    140.0
chol        293.0
fbs           0.0
restecg       0.0
thalach     170.0
exang         0.0
oldpeak       1.2
slope         1.0
ca            2.0
thal          3.0
Name: 237, dtype: float64
 [0]
The Person do not have heart disease
age          45.0
sex           0.0
cp            0.0
trestbps    138.0
chol        236.0
fbs           0.0
restecg       0.0
thalach     152.0
exang         1.0
oldpeak       0.2
slope         1.0
ca            0.0
thal          2.0
Name: 107, dtype: float64
 [1]
The person has heart disease
age          66.0
sex           1.0
cp            0.0
trestbps    120.0
chol        302.0
fbs           0.0
restecg       0.0
thalach     151.0
exang         0.0
oldpeak       0.4
slope         1.0
ca            0.0
thal          2.0
Name: 51, dtype: float64
 [0]
The Person do not have heart disease
age          52.0
sex           1.0
cp            1.0
trestbps    120.0
chol        325.0
fbs           0.0
restecg       1.0
thalach     172.0
exang         0.0
oldpeak       0.2
slope         2.0
ca            0.0
thal          2.0
Name: 45, dtype: float64
 [1]
The person has heart disease
age          49.0
sex           1.0
cp            2.0
trestbps    120.0
chol        188.0
fbs           0.0
restecg       1.0
thalach     139.0
exang         0.0
oldpeak       2.0
slope         1.0
ca            3.0
thal          3.0
Name: 208, dtype: float64
 [0]
The Person do not have heart disease
age          62.0
sex           0.0
cp            0.0
trestbps    160.0
chol        164.0
fbs           0.0
restecg       0.0
thalach     145.0
exang         0.0
oldpeak       6.2
slope         0.0
ca            3.0
thal          3.0
Name: 204, dtype: float64
 [0]
The Person do not have heart disease
age          49.0
sex           1.0
cp            2.0
trestbps    118.0
chol        149.0
fbs           0.0
restecg       0.0
thalach     126.0
exang         0.0
oldpeak       0.8
slope         2.0
ca            3.0
thal          2.0
Name: 267, dtype: float64
 [0]
The Person do not have heart disease
age          54.0
sex           0.0
cp            2.0
trestbps    135.0
chol        304.0
fbs           1.0
restecg       1.0
thalach     170.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 36, dtype: float64
 [1]
The person has heart disease
age          51.0
sex           0.0
cp            2.0
trestbps    140.0
chol        308.0
fbs           0.0
restecg       0.0
thalach     142.0
exang         0.0
oldpeak       1.5
slope         2.0
ca            1.0
thal          2.0
Name: 40, dtype: float64
 [1]
The person has heart disease
age          64.0
sex           1.0
cp            0.0
trestbps    128.0
chol        263.0
fbs           0.0
restecg       1.0
thalach     105.0
exang         1.0
oldpeak       0.2
slope         1.0
ca            1.0
thal          3.0
Name: 139, dtype: float64
 [0]
The Person do not have heart disease
age          58.0
sex           1.0
cp            1.0
trestbps    120.0
chol        284.0
fbs           0.0
restecg       0.0
thalach     160.0
exang         0.0
oldpeak       1.8
slope         1.0
ca            0.0
thal          2.0
Name: 172, dtype: float64
 [1]
The person has heart disease
age          39.0
sex           1.0
cp            0.0
trestbps    118.0
chol        219.0
fbs           0.0
restecg       1.0
thalach     140.0
exang         0.0
oldpeak       1.2
slope         1.0
ca            0.0
thal          3.0
Name: 212, dtype: float64
 [0]
The Person do not have heart disease
age          41.0
sex           1.0
cp            2.0
trestbps    112.0
chol        250.0
fbs           0.0
restecg       1.0
thalach     179.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 80, dtype: float64
 [1]
The person has heart disease
age          59.0
sex           1.0
cp            3.0
trestbps    170.0
chol        288.0
fbs           0.0
restecg       0.0
thalach     159.0
exang         0.0
oldpeak       0.2
slope         1.0
ca            0.0
thal          3.0
Name: 228, dtype: float64
 [1]
The person has heart disease
age          51.0
sex           1.0
cp            3.0
trestbps    125.0
chol        213.0
fbs           0.0
restecg       0.0
thalach     125.0
exang         1.0
oldpeak       1.4
slope         2.0
ca            1.0
thal          2.0
Name: 34, dtype: float64
 [0]
The Person do not have heart disease
age          53.0
sex           0.0
cp            2.0
trestbps    128.0
chol        216.0
fbs           0.0
restecg       0.0
thalach     115.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          0.0
Name: 48, dtype: float64
 [1]
The person has heart disease
age          46.0
sex           1.0
cp            2.0
trestbps    150.0
chol        231.0
fbs           0.0
restecg       1.0
thalach     147.0
exang         0.0
oldpeak       3.6
slope         1.0
ca            0.0
thal          2.0
Name: 196, dtype: float64
 [1]
The person has heart disease
age          57.0
sex           0.0
cp            0.0
trestbps    140.0
chol        241.0
fbs           0.0
restecg       1.0
thalach     123.0
exang         1.0
oldpeak       0.2
slope         1.0
ca            0.0
thal          3.0
Name: 298, dtype: float64
 [0]
The Person do not have heart disease
age          66.0
sex           0.0
cp            0.0
trestbps    178.0
chol        228.0
fbs           1.0
restecg       1.0
thalach     165.0
exang         1.0
oldpeak       1.0
slope         1.0
ca            2.0
thal          3.0
Name: 260, dtype: float64
 [0]
The Person do not have heart disease
age          70.0
sex           1.0
cp            2.0
trestbps    160.0
chol        269.0
fbs           0.0
restecg       1.0
thalach     112.0
exang         1.0
oldpeak       2.9
slope         1.0
ca            1.0
thal          3.0
Name: 240, dtype: float64
 [0]
The Person do not have heart disease
age          55.0
sex           1.0
cp            0.0
trestbps    160.0
chol        289.0
fbs           0.0
restecg       0.0
thalach     145.0
exang         1.0
oldpeak       0.8
slope         1.0
ca            1.0
thal          3.0
Name: 232, dtype: float64
 [0]
The Person do not have heart disease
age          49.0
sex           0.0
cp            0.0
trestbps    130.0
chol        269.0
fbs           0.0
restecg       1.0
thalach     163.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 135, dtype: float64
 [1]
The person has heart disease
age          53.0
sex           1.0
cp            0.0
trestbps    142.0
chol        226.0
fbs           0.0
restecg       0.0
thalach     111.0
exang         1.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          3.0
Name: 95, dtype: float64
 [0]
The Person do not have heart disease
age          70.0
sex           1.0
cp            1.0
trestbps    156.0
chol        245.0
fbs           0.0
restecg       0.0
thalach     143.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 145, dtype: float64
 [1]
The person has heart disease
age          57.0
sex           1.0
cp            2.0
trestbps    150.0
chol        168.0
fbs           0.0
restecg       1.0
thalach     174.0
exang         0.0
oldpeak       1.6
slope         2.0
ca            0.0
thal          2.0
Name: 9, dtype: float64
 [1]
The person has heart disease
age          68.0
sex           1.0
cp            2.0
trestbps    118.0
chol        277.0
fbs           0.0
restecg       1.0
thalach     151.0
exang         0.0
oldpeak       1.0
slope         2.0
ca            1.0
thal          3.0
Name: 86, dtype: float64
 [1]
The person has heart disease
age          67.0
sex           1.0
cp            0.0
trestbps    120.0
chol        237.0
fbs           0.0
restecg       1.0
thalach      71.0
exang         0.0
oldpeak       1.0
slope         1.0
ca            0.0
thal          2.0
Name: 272, dtype: float64
 [0]
The Person do not have heart disease
age          56.0
sex           1.0
cp            0.0
trestbps    130.0
chol        283.0
fbs           1.0
restecg       0.0
thalach     103.0
exang         1.0
oldpeak       1.6
slope         0.0
ca            0.0
thal          3.0
Name: 269, dtype: float64
 [0]
The Person do not have heart disease
age          62.0
sex           1.0
cp            0.0
trestbps    120.0
chol        267.0
fbs           0.0
restecg       1.0
thalach      99.0
exang         1.0
oldpeak       1.8
slope         1.0
ca            2.0
thal          3.0
Name: 198, dtype: float64
 [0]
The Person do not have heart disease
age          48.0
sex           1.0
cp            2.0
trestbps    124.0
chol        255.0
fbs           1.0
restecg       1.0
thalach     175.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            2.0
thal          2.0
Name: 90, dtype: float64
 [1]
The person has heart disease
age          53.0
sex           1.0
cp            0.0
trestbps    140.0
chol        203.0
fbs           1.0
restecg       0.0
thalach     155.0
exang         1.0
oldpeak       3.1
slope         0.0
ca            0.0
thal          3.0
Name: 169, dtype: float64
 [0]
The Person do not have heart disease
age          52.0
sex           1.0
cp            0.0
trestbps    108.0
chol        233.0
fbs           1.0
restecg       1.0
thalach     147.0
exang         0.0
oldpeak       0.1
slope         2.0
ca            3.0
thal          3.0
Name: 97, dtype: float64
 [0]
The Person do not have heart disease
age          37.0
sex           1.0
cp            2.0
trestbps    130.0
chol        250.0
fbs           0.0
restecg       1.0
thalach     187.0
exang         0.0
oldpeak       3.5
slope         0.0
ca            0.0
thal          2.0
Name: 1, dtype: float64
 [1]
The person has heart disease
age          44.0
sex           1.0
cp            0.0
trestbps    112.0
chol        290.0
fbs           0.0
restecg       0.0
thalach     153.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          2.0
Name: 185, dtype: float64
 [0]
The Person do not have heart disease
age          52.0
sex           1.0
cp            0.0
trestbps    128.0
chol        204.0
fbs           1.0
restecg       1.0
thalach     156.0
exang         1.0
oldpeak       1.0
slope         1.0
ca            0.0
thal          0.0
Name: 281, dtype: float64
 [1]
The person has heart disease
age          57.0
sex           1.0
cp            2.0
trestbps    150.0
chol        126.0
fbs           1.0
restecg       1.0
thalach     173.0
exang         0.0
oldpeak       0.2
slope         2.0
ca            1.0
thal          3.0
Name: 111, dtype: float64
 [1]
The person has heart disease
age          41.0
sex           1.0
cp            1.0
trestbps    135.0
chol        203.0
fbs           0.0
restecg       1.0
thalach     132.0
exang         0.0
oldpeak       0.0
slope         1.0
ca            0.0
thal          1.0
Name: 63, dtype: float64
 [1]
The person has heart disease
age          61.0
sex           1.0
cp            3.0
trestbps    134.0
chol        234.0
fbs           0.0
restecg       1.0
thalach     145.0
exang         0.0
oldpeak       2.6
slope         1.0
ca            2.0
thal          2.0
Name: 271, dtype: float64
 [1]
The person has heart disease
age          54.0
sex           1.0
cp            2.0
trestbps    150.0
chol        232.0
fbs           0.0
restecg       0.0
thalach     165.0
exang         0.0
oldpeak       1.6
slope         2.0
ca            0.0
thal          3.0
Name: 37, dtype: float64
 [1]
The person has heart disease
age          42.0
sex           1.0
cp            0.0
trestbps    140.0
chol        226.0
fbs           0.0
restecg       1.0
thalach     178.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 22, dtype: float64
 [1]
The person has heart disease
age          60.0
sex           0.0
cp            0.0
trestbps    150.0
chol        258.0
fbs           0.0
restecg       0.0
thalach     157.0
exang         0.0
oldpeak       2.6
slope         1.0
ca            2.0
thal          3.0
Name: 207, dtype: float64
 [0]
The Person do not have heart disease
age          54.0
sex           0.0
cp            2.0
trestbps    110.0
chol        214.0
fbs           0.0
restecg       1.0
thalach     158.0
exang         0.0
oldpeak       1.6
slope         1.0
ca            0.0
thal          2.0
Name: 88, dtype: float64
 [1]
The person has heart disease
age          68.0
sex           1.0
cp            2.0
trestbps    180.0
chol        274.0
fbs           1.0
restecg       0.0
thalach     150.0
exang         1.0
oldpeak       1.6
slope         1.0
ca            0.0
thal          3.0
Name: 203, dtype: float64
 [0]
The Person do not have heart disease
age          56.0
sex           0.0
cp            0.0
trestbps    200.0
chol        288.0
fbs           1.0
restecg       0.0
thalach     133.0
exang         1.0
oldpeak       4.0
slope         0.0
ca            2.0
thal          3.0
Name: 223, dtype: float64
 [0]
The Person do not have heart disease
age          67.0
sex           0.0
cp            0.0
trestbps    106.0
chol        223.0
fbs           0.0
restecg       1.0
thalach     142.0
exang         0.0
oldpeak       0.3
slope         2.0
ca            2.0
thal          2.0
Name: 143, dtype: float64
 [1]
The person has heart disease
age          58.0
sex           1.0
cp            0.0
trestbps    150.0
chol        270.0
fbs           0.0
restecg       0.0
thalach     111.0
exang         1.0
oldpeak       0.8
slope         2.0
ca            0.0
thal          3.0
Name: 202, dtype: float64
 [0]
The Person do not have heart disease
age          45.0
sex           1.0
cp            0.0
trestbps    115.0
chol        260.0
fbs           0.0
restecg       0.0
thalach     185.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 57, dtype: float64
 [1]
The person has heart disease
age          57.0
sex           0.0
cp            0.0
trestbps    128.0
chol        303.0
fbs           0.0
restecg       0.0
thalach     159.0
exang         0.0
oldpeak       0.0
slope         2.0
ca            1.0
thal          2.0
Name: 59, dtype: float64
 [1]
The person has heart disease
age          62.0
sex           0.0
cp            2.0
trestbps    130.0
chol        263.0
fbs           0.0
restecg       1.0
thalach      97.0
exang         0.0
oldpeak       1.2
slope         1.0
ca            1.0
thal          3.0
Name: 216, dtype: float64
 [0]
The Person do not have heart disease
age          45.0
sex           1.0
cp            0.0
trestbps    104.0
chol        208.0
fbs           0.0
restecg       0.0
thalach     148.0
exang         1.0
oldpeak       3.0
slope         1.0
ca            0.0
thal          2.0
Name: 42, dtype: float64
 [0]
The Person do not have heart disease
age          54.0
sex           1.0
cp            0.0
trestbps    124.0
chol        266.0
fbs           0.0
restecg       0.0
thalach     109.0
exang         1.0
oldpeak       2.2
slope         1.0
ca            1.0
thal          3.0
Name: 187, dtype: float64
 [0]
The Person do not have heart disease
age          52.0
sex           1.0
cp            2.0
trestbps    172.0
chol        199.0
fbs           1.0
restecg       1.0
thalach     162.0
exang         0.0
oldpeak       0.5
slope         2.0
ca            0.0
thal          3.0
Name: 8, dtype: float64
 [1]
The person has heart disease
age          41.0
sex           0.0
cp            2.0
trestbps    112.0
chol        268.0
fbs           0.0
restecg       0.0
thalach     172.0
exang         1.0
oldpeak       0.0
slope         2.0
ca            0.0
thal          2.0
Name: 122, dtype: float64
 [1]
The person has heart disease
age          69.0
sex           0.0
cp            3.0
trestbps    140.0
chol        239.0
fbs           0.0
restecg       1.0
thalach     151.0
exang         0.0
oldpeak       1.8
slope         2.0
ca            2.0
thal          2.0

Name: 19, dtype: float64
 [1]
The person has heart disease

IndexError: single positional indexer is out-of-bounds

In [17]:
import pickle
# open a file, where you ant to store the data
file = open('model.sav', 'wb')

# dump information to that file
pickle.dump(model, file)

In [18]:
# save the model to disk
filename = 'model2.sav'
pickle.dump(model, open(filename, 'wb'))
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, Y_test)

In [19]:
result

0.819672131147541

In [47]:
df.iloc[300]

age          68.0
sex           1.0
cp            0.0
trestbps    144.0
chol        193.0
fbs           1.0
restecg       1.0
thalach     141.0
exang         0.0
oldpeak       3.4
slope         1.0
ca            2.0
thal          3.0
target        0.0
Name: 300, dtype: float64